apiVersion: v1
kind: Namespace
metadata:
  name: profile-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: profile-system

spec:
  selector:
    matchLabels:
      app: profile

  template:
    metadata:
      labels:
        app: profile

    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: profile-api
          image: profile-image

          ports:
            - name: profile-api
              containerPort: 3000
            - name: profile-debug
              containerPort: 4000

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu

---
apiVersion: v1
kind: Service
metadata:
  name: profile-api
  namespace: profile-system
