apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: profile-system

spec:
  selector:
    matchLabels:
      app: profile

  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: profile

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
