apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: profile-system

spec:
  selector:
    matchLabels:
      app: profile

  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: profile

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
        - name: profile-api
          resources:
            requests:
              cpu: "1500m"
              memory: 500Mi
            limits:
              cpu: "1500m"
              memory: 500Mi

        #   volumeMounts:
        #     - name: vault
        #       mountPath: /vault

        # - name: metrics
        #   resources:
        #     requests:
        #       cpu: "500m"
        #       memory: 250Mi
        #     limits:
        #       cpu: "500m"
        #       memory: 250Mi
