apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: profile-system
spec:
  selector:
    matchLabels:
      app: profile
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: profile
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: profile-api
          resources:
            limits:
              cpu: "2000m" # Up to 2 full cores
            requests:
              cpu: "1000m" # Use 1 full cores
---
apiVersion: apps/v1
kind: Service
metadata:
  name: profile-service
  namespace: profile-system
spec:
  selector:
    app: profile
  type: ClusterIP
  ports:
    - name: profile-api
      port: 3000
      targetPort: profile-api
    - name: profile-debug
      port: 4000
      targetPort: profile-debug
