apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/profile/
patches:
  - path: ./dev-profile-patch.yaml
images:
  - name: profile-api-image
    newName: profile-api
    newTag: "1.0"
